docs/index.rst, docs/runtime-requirements.rst, pytest_mh/_private/fixtures.py, pytest_mh/_private/plugin.py
Add additional runtime requirement, skip test if requirement is not met.
```python
@pytest.mark.require(lambda client: "files-provider" in client.features)
```
=> markers: add require marker

pytest_mh/_private/fixtures.py
Teardown of <sssd_test_framework.hosts.client.ClientHost object at 0x7f461e9f79d0> can happen which triggers restoring backup data before teardown of sssd_test_framework.roles.client.Client object occurs to collect artifacts.
=> multihost: artifacts collection fix

pytest_mh/_private/fixtures.py
Previously, we only passed the ones that are in the test function
parameters but this was unnecessarily limitting.
Now we pass all fixtures defined for the topology combined with all
other fixtures available to the function.
=> markers: pass all defined fixtures to **kwargs in require marker

pytest_mh/utils/tc.py
New utility to perform traffic control operations such as slowing down the connection.
Resolves: https://github.com/next-actions/pytest-mh/issues/16
Depends on https://github.com/SSSD/sssd-ci-containers/pull/62
=> utils: perform traffic control operations

pytest_mh/_private/logging.py, pytest_mh/_private/misc.py, pytest_mh/_private/multihost.py, pytest_mh/_private/plugin.py, pytest_mh/utils/firewall.py, pytest_mh/utils/fs.py, pytest_mh/utils/services.py, pytest_mh/utils/tc.py
Each log message now looks like:
```
INFO     2023-11-14 14:31:27,646      client.test Writing file "/etc/sssd/sssd.conf"
```
This PR depends (first two commits) on https://github.com/next-actions/pytest-mh/pull/25
=> mh: always log a hostname in a log message

pytest_mh/_private/fixtures.py
Spaces in the test log path were causing  issues in artifact upload.
=> mh: Remove spaces and brackets from log paths.

pytest_mh/_private/fixtures.py, pytest_mh/_private/logging.py, pytest_mh/_private/multihost.py
Now roles, utils or individual tests can add custom artifacts to 
role.artifacts. This will be added to the list of host artifacts configured
in mhc.yaml.
=> artifacts: add support for dynamic artifacts list

pytest_mh/_private/fixtures.py
We only want to write the log file if a destination path is set.
---
This can be reproduced e.g. by  setting `--mh-collect-artifacts=never`
=> logs: do not create None directory

pytest_mh/utils/services.py
Calls `systemctl reset-failed $SERVICE` on all `*start()` methods.
This is required by changes to sssd-test-framework in https://github.com/SSSD/sssd-test-framework/pull/69
=> SYSTEMD: Reset the failed flag in all SystemdServices::*start() methods

docs/pytest.rst, pytest_mh/_private/fixtures.py, pytest_mh/_private/multihost.py, pytest_mh/_private/plugin.py
Artifacts are now extracted by default which is more convenient for
most use cases. For local run, you want to be able to quickly debug
failures and automation usually already compress everything in single
archive so it is again better to make it more easily accessible.
--mh-compress-artifacts was added to switch to the original behavior.
=> artifacts: extract archive by default

docs/index.rst, pytest_mh/__init__.py, pytest_mh/_private/multihost.py, readme.md
We would either store empty tarball (which is unreadable by tar) or fail
to extract it if artifact list is not empty but at the same time the
required files do not exist on the host.
=> multihost: do not attempt to write artifacts if none were collected

pytest_mh/_private/multihost.py
Domain and config are not likely to be used by users but on the
other hand these name are very likely to be used differently such
as "custom domain config" or "dns domain" or "identity domain"
and so on. Therefore it makes sense to prefix them.
Other fields are expected to be used so it does not makes sense
to prefix them but rather keep them short and clear.
=> multihost: add mh prefix to selected fields

.github/workflows/ci.yml
This makes it clear if there is issue in tests or dependency
installation.
=> ci: split tox package installation from testing

pytest_mh/utils/services.py
On centos-8 systemctl doesn't support '-P'
'--value --property' should work with both older and modern versions.
=> SYSTEMD: make `get_property()` with older 'systemctl'

docs/classes.rst, docs/quick-start.rst, docs/topology.rst, pytest_mh/__init__.py, pytest_mh/_private/data.py, pytest_mh/_private/fixtures.py, pytest_mh/_private/marks.py, pytest_mh/_private/misc.py, pytest_mh/_private/plugin.py, pytest_mh/_private/topology_controller.py, tests/test_misc.py
Topology controller can provide various topology related hooks.
Right now, it provides per-topology setup and teardown as well
as the possibility to skip all tests for this topology.
We can use it to automatically enroll client into domains or
setup trust. Doing this in ansible has its limitations for more
complex setups (such as multiple AD domains). Now we can do it
from pytest so we don't have to run the test suite multiple times,
each time with different environment.
=> add topology controller

pytest_mh/_private/fixtures.py, pytest_mh/_private/misc.py, pytest_mh/_private/multihost.py, pytest_mh/_private/topology_controller.py, tests/test_misc.py
Before we did not collect any artifacts and logged teardown to a setup phase if an exception was risen during setup.
Now, setup and teardown are fully separated which makes the code easier and it is also separated in the logs. Additionally, we now collect available artifacts so we can actually learn why the setup phase failed.
=> Produce better logs and collect artifacts on failed setup

pytest_mh/utils/fs.py
fs: switch to cp instead of mv in backup/restore
This workaround a problem of restoring files that are mounted in containers
like /etc/resolv.conf.
fs: remove path only if it is directory for write and upload
To keep file's attributes unless we want to explicitly overwrite them. This
also helps on container's special files that are mounted and cannot be
removed like /etc/resolv.conf.
=> fs: make write and restore work for files that are mounted in container

pytest_mh/_private/fixtures.py, pytest_mh/_private/multihost.py
For example, if we have SSSDUtils, we can automatically make it
to collect SSSD logs and database instead of relying on configuration
in mhc.yaml.
Additionally, it is possible to use prepare_artifacts to collect coredumps
from coredumpclt/journald and other stuff.
=> mh: support extra artifacts in host and utility as well

pytest_mh/__init__.py, pytest_mh/_private/multihost.py, pytest_mh/utils/firewall.py
Using inspect.getmembers calls getattr internally which evalutes
lazy properties as a side effect. This is undesirable and can
cause troubles in some cases.
This patch switches to metaclass magic. It also moves the decorators
outside MultihostUtility class for simpler use.
=> multihost: avoid using inspect.getmembers in MultihostUtility

pytest_mh/_private/fixtures.py, pytest_mh/_private/marks.py
This can be used to access fixtures from withing hosts and roles.
=> mh: add direct access fixture mapping

pytest_mh/_private/fixtures.py, pytest_mh/_private/plugin.py, pytest_mh/utils/auditd.py
This utility will collect auditd logs for each test. It can be also 
configured to report any AVC denial and optionally fail the test if AVC
denial is found.
=> utils: add Auditd

pytest_mh/utils/coredumpd.py
Collects generated core files from /var/lib/systemd/coredump and if there
are any, optionally fail the test.
=> utils: add Coredumpd

pytest_mh/_private/artifacts.py, pytest_mh/_private/errors.py, pytest_mh/_private/fixtures.py, pytest_mh/_private/multihost.py, pytest_mh/_private/plugin.py
python-3.11 brings ExceptionGroup feature which is very useful for
our use case where we need to teardown multiple objects eventhough
some of them failed.
With ExceptionGroup, no exception and its traceback is lost.
See:
https://peps.python.org/pep-0654/
=> errors: switch to ExceptionGroup

pytest_mh/utils/firewall.py
Direct rules have been deprecated for some time now, so we switch to using rich rules.
However, we need a specific policy to which the rule will be applied. This policy is permanent (a requirement) and is created at setup, deleted at teardown, and remains active during the whole test. Only the rules are dynamic.
This works on RHEL 8 thourgh 10.
=> FIREWALL: Use rich rules instead of direct rules

pytest_mh/_private/plugin.py
Now it is possible to use `@mh_fixture` instead of `@mh_fixture()`.
=> plugin: allow direct decoration with mh_fixture

pytest_mh/_private/plugin.py
The following pytest fixture syntax is now supported.
```
@mh_fixture
def fixt(client: Client):
setup()
yield
teardown()
```
=> plugin: make mh_fixture work with generators

pytest_mh/_private/multihost.py
This is reserved for custom configuration options to avoid potential
name collisions if we add more stuff.
=> multihost: add config field to MultihostDomain and MultihostConfig as well

pytest_mh/utils/journald.py
Usually, we want to only match logs for our program.
=> journald: add unit parameter to is_match and count

pytest_mh/_private/data.py, pytest_mh/_private/topology_controller.py
This method is inteded to be overwritten, therefore it should be public.
=> topology-controller: make _init a public method

pytest_mh/_private/marks.py
In addition to Topology and KnownTopologyBase values.
```
@pytest.mark.topology(TopologyMark(...))
@pytest.mark.topology([TopologyMark(...), ...])
```
=> topology-marker: allow to pass TopologyMark directly, make _CreateFromArgs public and docs improvements

pytest_mh/__init__.py, pytest_mh/_private/multihost.py, pytest_mh/_private/topology_controller.py
MultihostBackupHost: This is a base host that provides automatic host backup and restore functionality.
BackupTopologyController: This controller provides automatic backup and restore of the topology hosts.
=> multihost: add MultihostBackupHost and BackupTopologyController

pytest_mh/utils/journald.py
Running journalctl in pager (interactive) mode does not make any sense
in automated tests. On the other hand, we want to sent this parameter
by default to make sure it is never run in interactive mode.
=> journald: set no-pager parameter

pytest_mh/utils/journald.py
Otherwise an empty timestamp is used in "journalctl" as "since".
=> journald: set initial cursor

pytest_mh/utils/firewall.py
When blocking a host, its hostname is resolved using the `dig` command. If an IP address is provided, `dig` returns nothing and it is not blocked.
We need to check whether it is an IP address before launching `dig`. No matter whether the correct family is requested, do not call `dig` when an IP address is provided, in case the caller has already blocked the DNS host.
=> FIREWALL: Allow to block hosts by IP address

docs/articles/tips-and-tricks.rst, docs/articles/tips-and-tricks/building-command-line.rst
I think this is the last thing that was left undocumented.
=> docs: document CLIBuilder class in tips and tricks

.github/workflows/ci.yml, pytest_mh/_private/multihost.py, pytest_mh/conn/__init__.py, tests/test_conn.py
To make the code more portable to distributions that don't have bash in
/usr/bin.
=> conn: use /usr/bin/env to run the shell

pytest_mh/conn/ssh.py
When the timeout is set to 1 in LibsshSession(timeout=1), pylibssh no longer returns an exception for a wrong password SSH connect()
with pytest.raises(SSHAuthenticationError):
client.ssh("user1", "Wrong").connect()
Increase the minimum timeout a couple seconds here.
Regarding 'LibsshSession(timeout=1)', a very low value must be set here, to allow the timeout set in
client.host.conn.run(..., timeout=X)
to work as expected. This is due to code becoming blocked in libssh which is C not Python, but the Python signal is delayed until we get back to the Python code
=> Workaround timeout issue with SSH_AUTH_AGAIN

docs/articles/tips-and-tricks.rst, docs/articles/tips-and-tricks/preferred-topology.rst, pytest_mh/_private/data.py, pytest_mh/_private/plugin.py
Reducing test running time and system resources, we can now mark
a test with @pytest.mark.preferred_topology(KnownTopology.topology),
making the topology the single and default run unless the marker is
overridden. This is intended to be used for tests that do not need
to cover all topologies all the time.
=>  markers: new preferred_topology marker
